name: "Podcast Generator"
author: "Marta González"
description: "Generates a feed for a podcasr froma. YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commite's email address
    required: true
    default: ${{ github.actor}}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}